#!/bin/bash

GNUCAP=../src/gnucap

$GNUCAP -b t-20.gckt    |tee t-20.out
$GNUCAP -b t-21.gckt    |tee t-21.out
$GNUCAP -b t-22.gckt    |tee t-22.out
$GNUCAP    t-23.cmd     |tee t-23.out
$GNUCAP    t-24.cmd     |tee t-24.out
$GNUCAP -b t-25.gckt    |tee t-25.out


