#!/bin/bash

../src/gnucap -b function1.gckt |tee function1.out
../src/gnucap -b function2.gckt |tee function2.out
../src/gnucap -b function3.gckt |tee function3.out
../src/gnucap -b function4.gckt |tee function4.out

../src/gnucap -b function5.gckt |tee function5.out

../src/gnucap -b function6.gckt |tee function6.out
../src/gnucap -b function7.gckt |tee function7.out

echo SUMMARY:

for file in `ls function*.out`; do
    diff $file ./golden
done