#!/bin/bash

GNUCAP="../src/gnucap"

$GNUCAP -b global1.gckt |tee global1.out
$GNUCAP -b global2.gckt |tee global2.out
$GNUCAP -b global3.gckt |tee global3.out
$GNUCAP -b global4.gckt |tee global4.out
$GNUCAP -b global5.gckt |tee global5.out
$GNUCAP -b global6.gckt |tee global6.out

$GNUCAP -b global8.gckt |tee global8.out
$GNUCAP -b global9.gckt |tee global9.out

$GNUCAP -b global11.gckt |tee global11.out
$GNUCAP -b global12.gckt |tee global12.out

$GNUCAP -b global21.gckt |tee global21.out

echo "RESULTS <if no - it's ok>":
diff --ignore-matching-lines="Gnucap gnucap"  global1.out ./golden
diff --ignore-matching-lines="Gnucap gnucap"  global2.out ./golden
diff --ignore-matching-lines="Gnucap gnucap"  global3.out ./golden
diff --ignore-matching-lines="Gnucap gnucap"  global4.out ./golden
diff --ignore-matching-lines="Gnucap gnucap"  global5.out ./golden
diff --ignore-matching-lines="Gnucap gnucap"  global6.out ./golden

diff --ignore-matching-lines="Gnucap gnucap"  global8.out ./golden
diff --ignore-matching-lines="Gnucap gnucap"  global9.out ./golden

diff --ignore-matching-lines="Gnucap gnucap"  global11.out ./golden
diff --ignore-matching-lines="Gnucap gnucap"  global12.out ./golden

diff --ignore-matching-lines="Gnucap gnucap"  global21.out ./golden
