#!/bin/bash

CXX=g++44
GNUCAPDIR="../"
GNUCAP="../gnucap"
MODELGEN=$GNUCAPDIR/../modelgen/gnucap-modelgen 

#make -C ..

$MODELGEN  d_square.model
$CXX -c -O2 -g -I $GNUCAPDIR -fPIC -o d_square.o d_square.cc
$CXX -shared d_square.o -o d_square.so

